name: Test

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]

    name: Python ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - run: pixi install -e development
      - run: pixi run fmt
      - run: pixi run lint
      - run: pixi run types
      - run: pixi run test --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
